// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var imc = Imc.FromJson(jsonString);

namespace Lab.Models
{

    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class IMC
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("fechaRegistro")]
        public DateTimeOffset FechaRegistro { get; set; }

        [JsonProperty("peso")]
        public float Peso { get; set; }

        [JsonProperty("altura")]
        public float Altura { get; set; }

        [JsonProperty("imc")]
        public float Imc { get; set; }
    }

    public partial class IMC
    {
        public static List<IMC> FromJson(string json) => JsonConvert.DeserializeObject<List<IMC>>(json, Lab.Models.Converter.Settings);
    }

    public static class SerializeIMC
    {
        public static string ToJson(this List<IMC> self) => JsonConvert.SerializeObject(self, Lab.Models.Converter.Settings);
    }

    internal static class ConverterIMC
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
